### ISSUE TITLE
Error: PostError: network-failure

### ISSUE THREAD

**Issue by lencioni** [youngcw/actualplaid#6]
I am getting things set up for the first time and have run into an issue.

I have set up my Plaid account and have production access. After running `node index.js setup`, linking a bank, and proceeding past the "Are you done linking banks?" prompt, the setup immediately fails with the following error:

```
Error: PostError: network-failure
    at post (/path/to/actualplaid/node_modules/@actual-app/api/dist/app/bundle.api.js:45013:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handlers.subscribe-sign-in (/path/to/actualplaid/node_modules/@actual-app/api/dist/app/bundle.api.js:43923:29)
```

Any suggestions on what I might be able to try to get this working?

**Comment by TFenby** [comment]
Seeing the same just trying to run a regular sync. Last successful run was 3/23

**Comment by lencioni** [comment]
I added a bit of logging locally, and found this:

```
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
      at TLSSocket.emit (node:events:518:28)
      at TLSSocket._finishInit (node:_tls_wrap:1085:8)
      at ssl.onhandshakedone (node:_tls_wrap:871:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  }
```

I am using a self-signed certificate since I'm just running on localhost, so this makes some sense to me. I tried to use `NODE_EXTRA_CA_CERTS` to tell node to allow it, but had no luck, so I resorted to `NODE_TLS_REJECT_UNAUTHORIZED="0"` to see if I could get things moving a bit more freely.

This allowed me to finish linking an account, which is nice. Unfortunately, then when I run `node index.js import` I get this error:

```
Got messages from server 0
Importing transactions for account:  CHECKING from  2024-04-06 to 2024-04-05
PlaidError: INVALID_FIELD
    at rejectWithPlaidError (/path/to/actualplaid/node_modules/plaid/lib/plaidRequest.js:18:19)
    at /path/to/actualplaid/node_modules/plaid/lib/plaidRequest.js:101:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I added a bit more logging and I can now see that the error message says "end_date must be after start_date".
